// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXlIYyXqAAhU1pcZ1ZstjpLjcpocEINw8',
    appId: '1:483622794125:web:239d8a48468eec0f63c3c4',
    messagingSenderId: '483622794125',
    projectId: 'chatappflutter-987d0',
    authDomain: 'chatappflutter-987d0.firebaseapp.com',
    storageBucket: 'chatappflutter-987d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvspTzFpd4fWumTrS4FwqM-E64sjY368w',
    appId: '1:483622794125:android:9f9e7f1bb2df6d2763c3c4',
    messagingSenderId: '483622794125',
    projectId: 'chatappflutter-987d0',
    storageBucket: 'chatappflutter-987d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxH-tUzmrBowFa-KUnUHSl2k9mdRQad5c',
    appId: '1:483622794125:ios:ec7409def625b5d963c3c4',
    messagingSenderId: '483622794125',
    projectId: 'chatappflutter-987d0',
    storageBucket: 'chatappflutter-987d0.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxH-tUzmrBowFa-KUnUHSl2k9mdRQad5c',
    appId: '1:483622794125:ios:968c3c2624fd632063c3c4',
    messagingSenderId: '483622794125',
    projectId: 'chatappflutter-987d0',
    storageBucket: 'chatappflutter-987d0.appspot.com',
    iosBundleId: 'com.example.chatappFirebase.RunnerTests',
  );
}
